# Generated by Django 3.0 on 2021-08-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_row',
            name='Result_author_link',
            field=models.TextField(default=None, verbose_name='Ссылка на vk.com автора '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_row',
            name='Result_comment_link',
            field=models.TextField(default=5193, verbose_name='Ссылка на vk.com Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_row',
            name='Result_parentnote_link',
            field=models.TextField(default=156, verbose_name='Ссылка на vk.com К записи'),
            preserve_default=False,
        ),
    ]
