# Generated by Django 3.0 on 2021-08-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0002_auto_20210823_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result_row',
            name='Result_author_link',
        ),
        migrations.RemoveField(
            model_name='result_row',
            name='Result_comment_link',
        ),
        migrations.RemoveField(
            model_name='result_row',
            name='Result_parentnote_link',
        ),
    ]
