# Generated by Django 3.0 on 2021-08-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0003_auto_20210823_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_row',
            name='Result_author_link',
            field=models.TextField(default='default', verbose_name='Ссылка на vk.com автора '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_row',
            name='Result_comment_link',
            field=models.TextField(default='default', verbose_name='Ссылка на vk.com Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_row',
            name='Result_parentnote_link',
            field=models.TextField(default='default', verbose_name='Ссылка на vk.com К записи'),
            preserve_default=False,
        ),
    ]
