# Generated by Django 3.0 on 2021-08-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0004_auto_20210823_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAdressRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_adress', models.TextField(verbose_name='Адрес запроса')),
            ],
        ),
        migrations.RenameField(
            model_name='result_row',
            old_name='Result_author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='result_row',
            old_name='Result_comment_link',
            new_name='comment_link',
        ),
        migrations.RenameField(
            model_name='result_row',
            old_name='Result_comment',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='result_row',
            old_name='Result_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='result_row',
            old_name='Result_likescount',
            new_name='likescount',
        ),
        migrations.RenameField(
            model_name='result_row',
            old_name='Result_parentnote',
            new_name='parentpost_text',
        ),
        migrations.RemoveField(
            model_name='result_row',
            name='Result_author_link',
        ),
        migrations.RemoveField(
            model_name='result_row',
            name='Result_parentnote_link',
        ),
        migrations.AddField(
            model_name='result_row',
            name='author_avatar',
            field=models.TextField(default=0, verbose_name='Ссылка на аватар автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_row',
            name='author_id',
            field=models.PositiveIntegerField(default=0, verbose_name='id автора комментария'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_row',
            name='author_link',
            field=models.TextField(default=0, verbose_name='Ссылка на vk.com автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_row',
            name='comment_id',
            field=models.PositiveIntegerField(default=0, verbose_name='id комментария'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_row',
            name='parentpost_link',
            field=models.TextField(default=0, verbose_name='Ссылка на vk.com запись'),
            preserve_default=False,
        ),
    ]
