# Generated by Django 3.0 on 2021-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0005_auto_20210828_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupAdressRequested',
        ),
        migrations.AddField(
            model_name='result_row',
            name='requested_adress',
            field=models.TextField(default=1, verbose_name='Запрошенный адрес'),
            preserve_default=False,
        ),
    ]
