# Generated by Django 3.0 on 2021-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0007_remove_result_row_requested_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_row',
            name='author_id',
            field=models.IntegerField(verbose_name='id автора комментария'),
        ),
    ]
